# Generated by Django 3.2.5 on 2021-07-13 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('classe', models.IntegerField()),
                ('num_telephone', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=50)),
                ('situation', models.TextField()),
                ('date_ajoute', models.DateTimeField(default=django.utils.timezone.now)),
                ('etat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.etat')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profil')),
            ],
        ),
    ]
