# Generated by Django 3.2.5 on 2021-07-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nomparrain',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
